# Generated by Django 5.1.2 on 2024-10-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer_shoe_remove_project_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shoe',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='stock',
        ),
        migrations.AddField(
            model_name='shoe',
            name='color',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='size',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
